// Códigos de banderas de países de la UE para usar con emoji o API
const countryFlags = {
    'Àustria': 'AT',
    'Bèlgica': 'BE',
    'Bulgària': 'BG',
    'Croàcia': 'HR',
    'Xipre': 'CY',
    'República Txeca': 'CZ',
    'Dinamarca': 'DK',
    'Estònia': 'EE',
    'Finlàndia': 'FI',
    'França': 'FR',
    'Alemanya': 'DE',
    'Grècia': 'GR',
    'Hongria': 'HU',
    'Irlanda': 'IE',
    'Itàlia': 'IT',
    'Letònia': 'LV',
    'Lituània': 'LT',
    'Luxemburg': 'LU',
    'Malta': 'MT',
    'Països Baixos': 'NL',
    'Polònia': 'PL',
    'Portugal': 'PT',
    'Romania': 'RO',
    'Eslovàquia': 'SK',
    'Eslovènia': 'SI',
    'Espanya': 'ES',
    'Suècia': 'SE'
};